pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroup: 'resourcegroup-tfstate'
  storageAccount: 'terraformtfstateskip'
  container: 'tfstate'
  tfstateFile: 'terraform.tfstate'
  anyTfChanges: 'false'
  azureServiceConnection: 'azure new'

steps:
- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.14.7'

- task: TerraformTaskV4@4
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/skip-step'
    backendServiceArm: 'azure new'
    backendAzureRmResourceGroupName: '$(resourceGroup)'
    backendAzureRmStorageAccountName: '$(storageAccount)'
    backendAzureRmContainerName: '$(container)'
    backendAzureRmKey: '$(tfstateFile)'

- task: TerraformTaskV4@4
  displayName: 'terraform plan -out=tfplan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/skip-step'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'azure new'

- task: PowerShell@2
  displayName: 'Detect any terraform change'
  inputs:
    targetType: 'inline'
    pwsh: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/skip-step'
    script: |
      $planJson = terraform show -json tfplan
      $plan = $planJson | ConvertFrom-Json

      $actions = @()

      foreach ($resource in $plan.resource_changes) {
        if ($null -ne $resource.change -and $null -ne $resource.change.actions) {
          $actions += $resource.change.actions
        }
      }

      $actions = $actions | Sort-Object -Unique
      Write-Host "Terraform actions: $($actions -join ', ')"

      if (($actions -contains 'create') -or ($actions -contains 'update') -or ($actions -contains 'delete')) {
        Write-Host "Terraform will perform the following actions: $($actions -join ', ')"
        Write-Host "##vso[task.setvariable variable=anyTfChanges]true"
      }
      else {
        Write-Host "There is no change detected in Terraform tfplan file"
        Write-Host "##vso[task.setvariable variable=anyTfChanges]false"
      }

- task: TerraformTaskV4@4
  displayName: 'terraform apply tfplan'
  condition: eq(variables['anyTfChanges'], 'true')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/skip-step'
    commandOptions: 'tfplan'
    environmentServiceNameAzureRM: 'azure new'